name: "Bug"
description: "버그가 생겼나요?"
labels: ["🐞 Bug"]
body:
  - type: textarea
    attributes:
      label: Describe
      description: "[Description] 버그에 관한 설명을 작성해주세요."
      placeholder: "같은 QR을 두 번 스캔했는데 두 번째도 입장 처리됨"
  - type: textarea
    attributes:
      label: Additional
      description: "[추가사항] 별도로 알려줘야 할 사항이나 추가사항을 작성해주세요."
